### ISSUE TITLE
Enable searching for text in the online editor

### ISSUE THREAD

**Issue by glocq** [grame-cncm/fausteditor#2]
Pressing cmd-f when in the editor doesn't allow me to search, as it does on most other webpages. This holds both in Firefox, Chrome and Safari on MacOS 10.13.6.

Having the option to search in your code while using the editor would be very useful.

**Comment by sletz** [comment]
Have you tried the more sophisticated Faust Web IDE here: https://faustide.grame.fr ?

**Comment by glocq** [comment]
I hadn't! This looks better than the plain editor, is there a reason why the editor is linked on the frontpage rather than the IDE?

**Comment by sletz** [comment]
We are reworking the main site… old URLs still on it...

**Comment by sletz** [comment]
BTW out of curiosity, what are you using Faust for?

**Comment by glocq** [comment]
Ok, thank you for taking the time to answer. I'm converting a voice synthesis algorithm written in Max into Faust, for it to be usable on more platforms.

**Comment by sletz** [comment]
OK nice ! (hoping also the Faust version will run faster...)
