### ISSUE TITLE
Adding audio visualizer when clicking the play button.

### ISSUE THREAD

**Issue by vr-varad** [grame-cncm/fausteditor#9]
![Screenshot_1](https://github.com/grame-cncm/fausteditor/assets/114755221/389c2a83-063c-45b3-af36-6296c8624456)
while playing any audio can we add an audio visualizer for better visual effects?

**Comment by vr-varad** [comment]
@ijc8 what do u think about it?

**Comment by sletz** [comment]
Use the more sophisticated [Faust Web IDE](https://faustide.grame.fr).

**Comment by vr-varad** [comment]
@sletz Faust taking part in GSOC 2024?
